/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.viniciusgs.meuveiculo.view;

import br.com.viniciusgs.meuveiculo.controller.EstadoController;
import br.com.viniciusgs.meuveiculo.controller.PaisController;
import br.com.viniciusgs.meuveiculo.entity.Estado;
import br.com.viniciusgs.meuveiculo.entity.Pais;
import br.com.viniciusgs.meuveiculo.persistence.PersistenciaJPA;
import br.com.viniciusgs.meuveiculo.tables.TabelaEstadoConsulta;
import br.com.viniciusgs.meuveiculo.tables.TabelaPaisConsulta;
import br.com.viniciusgs.meuveiculo.utils.GerenciadorDeJanelas;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author FROTA01-PC
 */
public class TelaEstadoCadastro extends javax.swing.JInternalFrame {

    TelaEstadoCadastro telaCadastroPais = null;
    TelaPrincipal telaPrincipal = null;
    GerenciadorDeJanelas gerenciadorDeJanelas = new GerenciadorDeJanelas();

    /**
     * Creates new form TelaCadastroPais
     */
    public TelaEstadoCadastro() {
        initComponents();
        preencherCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idEstado = new javax.swing.JTextField();
        nomeEstado = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cboPais = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Cadastro de estados");
        setToolTipText("Cadastro de estados");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ID:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nome:");

        idEstado.setEnabled(false);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("País:");

        cboPais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboPaisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar))
                    .addComponent(idEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeEstado)
                    .addComponent(cboPais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnCancelar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        Estado estado = new Estado();
        EstadoController estadoController = new EstadoController();
        PaisController paisController = new PaisController();
        TabelaEstadoConsulta tabelaEstadoConsulta = new TabelaEstadoConsulta();
        try {
            if (!nomeEstado.getText().isEmpty()) {
                estado.setNome(nomeEstado.getText());
            } else {
                JOptionPane.showMessageDialog(null, "Favor preencher o nome do Estado");
            }
            Pais pais = (Pais) paisController.retornarIdPais(cboPais.getSelectedItem().toString());
            estado.setPais(pais);
            estadoController.cadastrar(estado);
            
            List<Estado> estadoTabela = estadoController.listarEstado();
            tabelaEstadoConsulta.carregarTabelaEstado(estadoTabela);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível cadastrar o Estado");
            System.out.println("Erro de cadastro. " + e);
        }


    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limparCampos();        
        
        PaisController paisController = new PaisController();
        String pais = cboPais.getSelectedItem().toString();
        System.out.println("País no combobox: " +pais);
        //System.out.println("País: " + pais);
        //List<Pais> paisLista = paisController.retornarIdPais(pais);
        //Pais pais = (Pais) cboPais.getSelectedItem();
        System.out.println("Pais retornado: ");
        //paisController.buscarPaisPorNome(pais);
        System.out.println("País retorno: " + paisController.retornarIdPais(pais));

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cboPaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboPaisMouseClicked

    }//GEN-LAST:event_cboPaisMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cboPais;
    private javax.swing.JTextField idEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nomeEstado;
    // End of variables declaration//GEN-END:variables

    public void limparCampos() {
        idEstado.setText("");
        nomeEstado.setText("");
    }

    public void carregarJanela() {

        if (telaCadastroPais == null) {
            telaCadastroPais = new TelaEstadoCadastro();
            telaPrincipal.DesktopPanel.add(telaCadastroPais);
        }
        if (!telaCadastroPais.isVisible()) {
            telaCadastroPais.setVisible(true);
        }
        telaCadastroPais.toFront();
        gerenciadorDeJanelas.setPosicao(telaCadastroPais);
    }

    private void preencherCombo() {
        try {
            PaisController paisController = new PaisController();
            List<Pais> pais = paisController.listarPais();

            // Adicionando os dados do ArrayList no JComboBox
            cboPais.addItem("-Selecione-");
            for (int i = 0; i < pais.size(); i++) {

                // Adicionando o nome do convênio ao JComboBox
                cboPais.addItem(pais.get(i).getNome());

            } // fecha for

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro! " + e.getMessage());
        } // fecha catch
    }
}
